spring.application.name=api

# Conexão com o Banco (Injetada via .env ou variáveis de ambiente)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Atualização automática das tabelas pelo Hibernate
spring.jpa.hibernate.ddl-auto=update

# DESENVOLVIMENTO: Mostra o SQL gerado no console de forma formatada
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

